CREATE TABLE  `tpequipos`.`equipos` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_TECNICO` int(11) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=19 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`formacion_suplentes` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_EQ_ID` int(11) NOT NULL,
  `J_INDICE` int(11) NOT NULL,
  PRIMARY KEY (`J_ID`,`J_EQ_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`formacion_titulares` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_EQ_ID` int(11) NOT NULL,
  `J_INDICE` int(11) NOT NULL,
  PRIMARY KEY (`J_ID`,`J_EQ_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`formaciones` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`habilidad` (
  `H_ID` int(11) NOT NULL AUTO_INCREMENT,
  `H_VALOR` int(11) NOT NULL,
  `H_POSICION` varchar(20) NOT NULL,
  `J_JD_ID` int(11) DEFAULT NULL,
  `J_INDICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`H_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=283 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`jugadores` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_NOMBRE` varchar(20) NOT NULL,
  `J_APELLIDO` varchar(20) NOT NULL,
  `J_NRO` int(11) NOT NULL,
  `J_INDICE` int(11) DEFAULT NULL,
  `J_EQ_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=153 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`partidoscopa` (
  `J_ID` int(11) NOT NULL,
  `J_GOLES_PENALES_1` int(11) DEFAULT NULL,
  `J_GOLES_PENALES_2` int(11) DEFAULT NULL,
  `J_PARTIDO1` int(11) DEFAULT NULL,
  `J_PARTIDO2` int(11) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`partidossimples` (
  `J_ID` int(11) NOT NULL,
  `J_GOLES_EQUIPO_1` int(11) DEFAULT NULL,
  `J_GOLES_EQUIPO_2` int(11) DEFAULT NULL,
  `J_EQUIPO1` int(11) DEFAULT NULL,
  `J_EQUIPO2` int(11) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`tecnicos` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_NOMBRE` varchar(20) DEFAULT NULL,
  `J_APELLIDO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`titulares` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_JUGADOR` int(11) NOT NULL,
  `H_POSICION` varchar(20) NOT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=53 DEFAULT CHARSET=latin1

