CREATE TABLE  `tpequipos`.`equipos` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`habilidad` (
  `H_ID` int(11) NOT NULL AUTO_INCREMENT,
  `H_VALOR` int(11) NOT NULL,
  `H_POSICION` varchar(20) NOT NULL,
  `J_JD_ID` int(11) DEFAULT NULL,
  `J_INDICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`H_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`jugadores` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_NOMBRE` varchar(20) NOT NULL,
  `J_APELLIDO` varchar(20) NOT NULL,
  `J_NRO` int(11) NOT NULL,
  `J_EQ_ID` int(11) DEFAULT NULL,
  `J_INDICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin1

CREATE TABLE  `tpequipos`.`partidos` (
  `J_ID` int(11) NOT NULL AUTO_INCREMENT,
  `J_GOLES_PARTIDO1` int(11) NOT NULL,
  `J_GOLES_PARTIDO2` int(11) NOT NULL,
  PRIMARY KEY (`J_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1


